Update helm-diff.yml

diff --git a/.github/workflows/helm-diff.yml b/.github/workflows/helm-diff.yml
--- a/.github/workflows/helm-diff.yml
+++ b/.github/workflows/helm-diff.yml
@@ -202,8 +202,11 @@ jobs:
           GITHUB_REPOSITORY: ${{ github.repository }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DIFF_TXT_PATH: diff.txt
+          PYTHONUNBUFFERED: "1"
         run: |
-          python .github/scripts/extract_image_info.py
+          echo "Starting extract_image_info.py..."
+          python .github/scripts/extract_image_info.py || { echo "❌ Script failed!"; exit 1; }
+          echo "Finished extract_image_info.py!"
 
       - name: Attempt to Pull Extracted Images
         id: pull_helm_images
