Update helm-diff.yml

diff --git a/.github/workflows/helm-diff.yml b/.github/workflows/helm-diff.yml
--- a/.github/workflows/helm-diff.yml
+++ b/.github/workflows/helm-diff.yml
@@ -207,7 +207,7 @@ jobs:
           DIFF_TXT_PATH: diff.txt
         run: |
           echo "Starting extract_image_info.py..."
-          cat diff.txt | python .github/scripts/extract_image_info.py || { echo "❌ Script failed!"; exit 1; }
+          python .github/scripts/extract_image_info.py || { echo "❌ Script failed!"; exit 1; }
           echo "Finished extract_image_info.py!"
 
       - name: Attempt to Pull Extracted Images
